export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const JSONTEXTBOOK_GET_SUCCESS = 'JSONTEXTBOOK_GET_SUCCESS';
export const TEXTBOOK_LOADING = 'TEXTBOOK_LOADING';
export const TEXTBOOKS_GET_SUCCESS = 'TEXTBOOKS_GET_SUCCESS';
export const TEXTBOOKS_GET_ERROR = 'TEXTBOOKS_GET_ERROR';
export const TEXTBOOK_GET_SUCCESS = 'TEXTBOOK_GET_SUCCESS';
export const TEXTBOOK_GET_ERROR = 'TEXTBOOK_GET_ERROR';
export const TEXTBOOK_CREATE_SUCCESS = 'TEXTBOOK_CREATE_SUCCESS';
export const TEXTBOOK_CREATE_ERROR = 'TEXTBOOK_CREATE_ERROR';
export const TEXTBOOK_DELETE_SUCCESS = 'TEXTBOOK_DELETE_SUCCESS';
export const TEXTBOOK_DELETE_ERROR = 'TEXTBOOK_DELETE_ERROR';

export const CURRICULUMS_GET_SUCCESS = 'CURRICULUMS_GET_SUCCESS';
export const CURRICULUMS_GET_ERROR = 'CURRICULUMS_GET_ERROR';