name: "Build"

on:
  push:
    branches: 
      - "master"
    paths-ignore:
      - '**.md'
    tags:
      - "!*"

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] #[macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Install Node.js, Npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Pack
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} yarn electron:pack
        shell: bash
        
      - name: Copy build files
        run: |
          mkdir build
          cp -r dist/assets build
          cp dist/index.html build
          
      - name: Deploy
        run: GH_TOKEN=${{ secrets.GH_TOKEN }} yarn deploy
        shell: bash
        
      - uses: bbonkr/get-version-action@v1.0.4
        id: get_version
        with:
          project: "./package.json"

      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Change exe name
        run: mv "dist/topolar_textbook_editor Setup ${{ steps.get_version.outputs.version }}.exe" "dist/topolar_textbook_editor-Setup-${{ steps.get_version.outputs.version }}.exe"
        
      - name: Change assets files dir
        run: |
          mkdir dist/release
          mv dist/latest.yml dist/release
          mv dist/topolar_textbook_editor-Setup-${{ steps.get_version.outputs.version }}.exe dist/release
          
      - name: Upload Assets
        uses: csexton/release-asset-action@v2
        with:
          pattern: "dist/release/*"
          github-token: ${{ secrets.GH_TOKEN }}
          release-url: ${{ steps.latest_release_info.outputs.upload_url }}
